### ISSUE TITLE
transport.outbound.Call should accept params as interface?

### ISSUE THREAD

**Issue by yzlai** [nickw444/miio-go#2]
According to Payloads section in [Protocol Specification](https://github.com/OpenMiHome/mihome-binary-protocol/blob/master/doc/PROTOCOL.md) reference, params could be any kind of interfaces instead of []string in [current implementation](https://github.com/nickw444/miio-go/blob/master/protocol/transport/outbound.go#L151-L160)?

**Comment by nickw444** [comment]
Ah! Definitely an oversight of my own. Would you be willing to make a pull request?
